### PR TITLE
Added "Buffer" type video module for uploading custom rgb images..

### PR DESCRIPTION
**Pull request by XrizZ**
rather than grabbing frames from files or webcams.

Signed-off-by: XrizZ

### CODE REVIEW

**Comment by ThorstenBux** [comment]
That is definitely interesting. Could you please have a look at the CI build issues and let me know if you can make sense of the error message and potentially fix them.

Cheers

**Comment by XrizZ** [comment]
Sorry about that, Cmake should be able to run now - forgot to add one file.

**Comment by ThorstenBux** [comment]
Still failing 
```
FAILED: /opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang  --target=x86_64-none-linux-android --gcc-toolchain=/opt/android-ndk/toolchains/x86_64-4.9/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk/sysroot -DARVIDEO_INPUT_ANDROID -DARVIDEO_INPUT_BUFFER -DARVIDEO_INPUT_DEFAULT_ANDROID -DARVIDEO_INPUT_DUMMY -DARVIDEO_INPUT_IMAGE -DARX_EXPORTS=1 -DARX_TARGET_PLATFORM_ANDROID=1 -IARX/AR/include -I../../../../../../../ARX/ARVideo/include -I../../../../../../../depends/android/include -I../../../../../../../ARX/ARVideo/../AR/include -I../../../../../../../ARX/ARVideo/../ARUtil/include -isystem /opt/android-ndk/sysroot/usr/include/x86_64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -O2 -DNDEBUG  -fPIC -MD -MT ARX/ARVideo/CMakeFiles/ARVideo.dir/video2.c.o -MF ARX/ARVideo/CMakeFiles/ARVideo.dir/video2.c.o.d -o ARX/ARVideo/CMakeFiles/ARVideo.dir/video2.c.o   -c /bitrise/src/Source/ARX/ARVideo/video2.c
  In file included from /bitrise/src/Source/ARX/ARVideo/video2.c:78:
  /bitrise/src/Source/ARX/ARVideo/Buffer/videoBuffer.h:66:2: error: unknown type name 'BYTE'
          BYTE*              userBufferPointer;
          ^
  1 error generated.
  ninja: build stopped: subcommand failed.
```

**Comment by XrizZ** [comment]
Fixed an issue, but still not sure why LInux and iOS won't build. Windows and Android are fine. Can you post the logs please? I can't see them through the bitrise app.

**Comment by ThorstenBux** [comment]
@XrizZ on Linux: ```CMake Error: The current CMakeCache.txt directory /bitrise/src/Source/CMakeCache.txt is different than the directory c:/Users/Chris/Desktop/artoolkitX_mine/Source where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
``` 
might be an absolute path somewhere

**Comment by ThorstenBux** [comment]
macos is the same ```CMake Error: The current CMakeCache.txt directory /Users/vagrant/git/Source/CMakeCache.txt is different than the directory c:/Users/Chris/Desktop/artoolkitX_mine/Source where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
```

**Comment by XrizZ** [comment]
@ThorstenBux thanks, the issue was just the CMakeCache.txt being in the repository, which it shouldnt. Whats the last remaining error for macos?

**Comment by ThorstenBux** [comment]
```CompileC build-ios/ARX/ARVideo/artoolkitX.build/Release-iphoneos/ARVideo.build/Objects-normal/arm64/videoBuffer.o ARX/ARVideo/Buffer/videoBuffer.c normal arm64 c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/vagrant/git/Source
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/vagrant/.bitrise/tools:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/go/libexec/bin:/Users/vagrant/go/bin:/Users/vagrant/bitrise/tools/cmd-bridge/bin/osx"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch arm64 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -Wno-trigraphs -fpascal-strings -O3 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DCMAKE_INTDIR=\"Release-iphoneos\" -DARX_TARGET_PLATFORM_IOS=1 -DARX_EXPORTS=1 -DARVIDEO_INPUT_DUMMY -DARVIDEO_INPUT_IMAGE -DARVIDEO_INPUT_BUFFER -DARVIDEO_INPUT_AVFOUNDATION -DARVIDEO_INPUT_DEFAULT_AVFOUNDATION -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.3.sdk -fstrict-aliasing -Wdeprecated-declarations -miphoneos-version-min=8.0 -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -I/Users/vagrant/git/Source/build-ios/ARX/ARVideo/Release-iphoneos/include -I/Users/vagrant/git/Source/build-ios/ARX/AR/include -I/Users/vagrant/git/Source/ARX/ARVideo/include -I/Users/vagrant/git/Source/depends/ios/include -I/Users/vagrant/git/Source/ARX/ARVideo/../AR/include -I/Users/vagrant/git/Source/ARX/ARVideo/../ARUtil/include -I/Users/vagrant/git/Source/build-ios/ARX/ARVideo/artoolkitX.build/Release-iphoneos/ARVideo.build/DerivedSources/arm64 -I/Users/vagrant/git/Source/build-ios/ARX/ARVideo/artoolkitX.build/Release-iphoneos/ARVideo.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/vagrant/git/Source/build-ios/ARX/ARVideo/Release-iphoneos -integrated-as -integrated-as -DNDEBUG -MMD -MT dependencies -MF /Users/vagrant/git/Source/build-ios/ARX/ARVideo/artoolkitX.build/Release-iphoneos/ARVideo.build/Objects-normal/arm64/videoBuffer.d --serialize-diagnostics /Users/vagrant/git/Source/build-ios/ARX/ARVideo/artoolkitX.build/Release-iphoneos/ARVideo.build/Objects-normal/arm64/videoBuffer.dia -c /Users/vagrant/git/Source/ARX/ARVideo/Buffer/videoBuffer.c -o /Users/vagrant/git/Source/build-ios/ARX/ARVideo/artoolkitX.build/Release-iphoneos/ARVideo.build/Objects-normal/arm64/videoBuffer.o
/Users/vagrant/git/Source/ARX/ARVideo/Buffer/videoBuffer.c:220:2: error: implicit declaration of function 'arUtilTimeSinceEpoch' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        arUtilTimeSinceEpoch(&vid->buffer.time.sec, &vid->buffer.time.usec);
        ^```

**Comment by ThorstenBux** [comment]
That is actually an iOS compilation error

**Comment by XrizZ** [comment]
Thanks @ThorstenBux - its fixed now! I'm hopeful that the feature can be merged into your master branch now. Cheers!

**Comment by ThorstenBux** [comment]
@XrizZ if you can spare some time could you write down some documentation on how to use your feature?

@philip-lamb Could you please review and merge if approved, tests are all good.

**Comment by martial** [comment]
Hi,

First of all – thanks for this amazing woek!
I wonder if there was some news regarding this pull request.

I've been trying to make it work with 2D markers, but still no result ( zero detection )
@XrizZ Any chance we can be in touch so I can understand & help to make this feature happen ?

**Comment by XrizZ** [comment]
@martial Sure thing, let me know how I can help!

**Comment by martial** [comment]
Any chance you can post / send a working example of your implementation ? 
I've been trying to send RGB buffer + 2D marker, with no luck.
I wonder what is doing your LoadImageUsingOpenCV method for example.

Then, surely this is not the right place to go forward with this, any contact where I can reach you ? 
Many thanks !

**Comment by XrizZ** [comment]
@martial send me an email on my public GitHub address: 38349874+XrizZ@users.noreply.github.com

I'll be able to send you a sample file back to your email next week. Unfortunately, I won't have access to the fiels sooner.. sorry.

**Comment by philip-lamb** [comment]
Sorry that this contribution has sat unmerged. I will take a look at it in the next 24 hours.

**Comment by philip-lamb** [comment]
Closing this now after all this time, as it has been made obsolete by #160 .

**Pull request closed without merging**
